logRetentionInDays: 30
tags:
  service-name: ss-monitors
  developed-by: Nynu
  deployed-with: serverless
webhooks:
  memberNotification: ${ssm:team-monitor-webhook-url}
  rosterMonitoring: ${ssm:discord-monitoring-webhook-url}
  runs: ${ssm:runs-channel-webhook-url}
updateRoster:
  queueUrl: ${ssm:update-roster-queue-url}
  queueArn: ${ssm:update-roster-queue-arn}
roster:
  googleCredentials: ${ssm(raw):roster-google-credentials}
  spreadsheetId: ${ssm:roster-spreadsheet-id}