name: "Setup Terraform"

inputs:
  terraform-version:
    description: "Terraform version to use"
    required: true
    default: 1.5.4

runs:
  using: "composite"
  steps:
    - name: Setup Terraform ${{ inputs.terraform-version }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}