name: Deploy

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup AWS Credentials
        uses: ./.github/actions/setup-aws-credentials
        with:
          deployment_ci_role: arn:aws:iam::950051275670:role/github-actions
      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
      - name: Terraform Init
        run: terraform init 
      - name: Deploy Terraform
        run: terraform apply -auto-approve

  serverless-deploy:
    runs-on: ubuntu-latest
    needs: terraform-deploy
    timeout-minutes: 10
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM CI
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Check Types
        run: npm run check-types
      - name: Setup AWS Credentials
        uses: ./.github/actions/setup-aws-credentials
        with:
          deployment_ci_role: arn:aws:iam::950051275670:role/github-actions
      - name: Deploy Serverless
        run: npm run deploy